runtime: python312
instance_class: F2

env_variables:
  SECRET_KEY: 'django-insecure-3&sutc15)!x_fj$u7pi@+5x&r3ile24!r64x&l)n#-r4$ue&#+'
  DEBUG: 'False'  # Set to False in production!
  DJANGO_SETTINGS_MODULE: 'credible.settings'

handlers:
- url: /static
  static_dir: static/
  secure: optional

- url: /media
  static_dir: media/
  secure: optional

- url: /.*
  script: auto
  secure: optional

entrypoint: bash startup.sh

automatic_scaling:
  min_instances: 0
  max_instances: 10